<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[if IE]><html xmlns="http://www.w3.org/1999/xhtml" class="ie"><![endif]-->
<!--[if !IE]><!-->
<html xmlns="http://www.w3.org/1999/xhtml" lang="sp" style="font-family: sans-serif; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; font-size: 10px; -webkit-tap-highlight-color: rgba(0,0,0,0);" xml:lang="sp">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<!--Librerias bootstrap y Jquery-->	

	
	
		<!-- Fin Librerias bootstrap y Jquery-->
		<title></title>
	
	</head>
	<body style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 14px; line-height: 1.42857143; background-color: #fff; margin: 0;" bgcolor="#fff">
	@php
		$data 	= Session::get('cart');
		$i = 1;
	@endphp
		<div class="container" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; padding-right: 15px; padding-left: 15px; margin-right: auto; margin-left: auto; width: 1170px;">
			<div class="row" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; margin-right: -15px; margin-left: -15px;">
			  <div class="col-xs-12 col-md-12 text-left" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; text-align: left; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 100%;" align="left"><h3 style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; orphans: 3; widows: 3; page-break-after: avoid; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; margin-top: 20px; margin-bottom: 10px; font-size: 24px;">Nueva Compra Softecol</h3></div>			
			</div>
			<div class="row" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; margin-right: -15px; margin-left: -15px;">
				<div class="col-xs-0 col-md-3" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 25%;"></div>	
				<div class="col-xs-12 col-md6 text-center" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; text-align: center; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 100%;" align="center"><h3 style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; orphans: 3; widows: 3; page-break-after: avoid; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; margin-top: 20px; margin-bottom: 10px; font-size: 24px;"><img src="phone.png" class="img-circle" alt="Softecol" width="60" height="60" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; page-break-inside: avoid; max-width: 100% !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; vertical-align: middle; border-radius: 50%; border: 0;" /></h3></div>
				<div class="col-xs-0 col-md-3" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 25%;"></div>			  
			</div>
			<div class="row" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; margin-right: -15px; margin-left: -15px;">
				<div class="col-xs-12 text-justify" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; text-align: justify; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 100%;" align="justify"><h4 style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; margin-top: 10px; margin-bottom: 10px; font-size: 18px;"></h4><p style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; orphans: 3; widows: 3; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; margin: 0 0 10px;">Se ha realizado una nueva compra en Softecol, gracias por preferirnos.
														 A continuación presentamos el resumen de los produtos adquiridos, junto con el metodo de pago seleccionado:
														   </p><p style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; orphans: 3; widows: 3; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; margin: 0 0 10px;">
				</p></div>
		   </div>
		   <br style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;" />
		     <div class="table-responsive" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; min-height: .01%; overflow-x: auto; width: 100%; margin-bottom: 15px; overflow-y: hidden; -ms-overflow-style: -ms-autohiding-scrollbar; border: 1px solid #ddd;">          
				  <table class="table" style="border-spacing: 0; border-collapse: collapse !important; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; width: 100%; max-width: 100%; margin-bottom: 0; background-color: transparent;" bgcolor="transparent">
					<thead style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; display: table-header-group; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">
					  <tr style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; page-break-inside: avoid; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">
						<th style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; text-align: left; line-height: 1.42857143; vertical-align: bottom; border-top-color: #ddd; border-top-width: 0; border-top-style: solid; border-bottom-color: #ddd; border-bottom-width: 2px; border-bottom-style: solid; white-space: nowrap; padding: 8px;" align="left" bgcolor="#fff !important" valign="bottom">#</th>
						<th style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; text-align: left; line-height: 1.42857143; vertical-align: bottom; border-top-color: #ddd; border-top-width: 0; border-top-style: solid; border-bottom-color: #ddd; border-bottom-width: 2px; border-bottom-style: solid; white-space: nowrap; padding: 8px;" align="left" bgcolor="#fff !important" valign="bottom">Producto</th>
						<th style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; text-align: left; line-height: 1.42857143; vertical-align: bottom; border-top-color: #ddd; border-top-width: 0; border-top-style: solid; border-bottom-color: #ddd; border-bottom-width: 2px; border-bottom-style: solid; white-space: nowrap; padding: 8px;" align="left" bgcolor="#fff !important" valign="bottom">Cantidad</th>
						<th style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; text-align: left; line-height: 1.42857143; vertical-align: bottom; border-top-color: #ddd; border-top-width: 0; border-top-style: solid; border-bottom-color: #ddd; border-bottom-width: 2px; border-bottom-style: solid; white-space: nowrap; padding: 8px;" align="left" bgcolor="#fff !important" valign="bottom">Valor</th>
					  </tr>
					</thead>
					<tbody style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">			
					@foreach($data as $key => $value)
					  <tr style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; page-break-inside: avoid; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top">{{$i}}</td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top">{{ $value['descripcion'] }}</td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top">{{$value['cantidad']}}</td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top">{{$value['precio']}}</td>						
					  </tr>
					  @php
					  	$i++;
					 @endphp
					 @endforeach 
					 <tr style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; page-break-inside: avoid; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">
					 	<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"></td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"></td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"><strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">Total Inicial:</strong></td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"><strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">{{$total['valbru']}}</strong></td>
					</tr>
					<tr style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; page-break-inside: avoid; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">
					 	<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"></td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"></td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"><strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">Iva:</strong></td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"><strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">{{$total['ivacli']}}</strong></td>
					</tr>
					<tr style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; page-break-inside: avoid; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">
					 	<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"></td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"></td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"><strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">Gastos Financieros:</strong></td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"><strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">{{$total['gasfin']}}</strong></td>
					</tr>
					<tr style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; page-break-inside: avoid; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">
					 	<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"></td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"></td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"><strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">Gastos de envio:</strong></td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"><strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">{{$total['gasenv']}}</strong></td>
					</tr>
					<tr style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; page-break-inside: avoid; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">	
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"></td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"></td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"><strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">Total a Pagar:</strong></td>
						<td style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; background-color: #fff !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; line-height: 1.42857143; vertical-align: top; border-top-color: #ddd; border-top-width: 1px; border-top-style: solid; white-space: nowrap; padding: 8px;" bgcolor="#fff !important" valign="top"><strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;">{{$total['totcli']}}</strong></td>
					  </tr>
					</tbody>
				  </table>
			</div>
			<div class="row" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; margin-right: -15px; margin-left: -15px;">
				<div class="col-xs-12 text-justify" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; text-align: justify; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 100%;" align="justify"><h3 style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; orphans: 3; widows: 3; page-break-after: avoid; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; margin-top: 20px; margin-bottom: 10px; font-size: 24px;"><pre style="overflow: auto; font-family: Menlo,Monaco,Consolas,'Courier New',monospace; font-size: 13px; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; page-break-inside: avoid; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; display: block; line-height: 1.42857143; word-break: break-all; word-wrap: break-word; border-radius: 4px; background-color: #f5f5f5; margin: 0 0 10px; padding: 9.5px; border: 1px solid #ccc;">Metodo de pago seleccionado:<strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"> Efectivo</strong> ----- Estado: <strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"> Pendiente de pago/entrega</strong></pre></h3>
				</div>
		   </div>
		   @if ($total['metpag'] == 3)
		   <div class="row" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; margin-right: -15px; margin-left: -15px;">
				<div class="col-xs-12 text-justify" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; text-align: justify; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 100%;" align="justify"><h3 style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; orphans: 3; widows: 3; page-break-after: avoid; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; margin-top: 20px; margin-bottom: 10px; font-size: 24px;"><pre style="overflow: auto; font-family: Menlo,Monaco,Consolas,'Courier New',monospace; font-size: 13px; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; page-break-inside: avoid; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; display: block; line-height: 1.42857143; word-break: break-all; word-wrap: break-word; border-radius: 4px; background-color: #f5f5f5; margin: 0 0 10px; padding: 9.5px; border: 1px solid #ccc;">
					Datos de pago - PayU
					<ul type = square>
						<li>Referencia de compra:<strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"> {{ $total['reference_sale'] }}</strong>
						<li>Fecha reporte de transacci&oacute;n:<strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"> {{ $total['fectx'] }}</strong>
						<li>Direcci&oacute;n de entrega:<strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"> {{ $total['shipping_address'] }}</strong>
						<li>Tel&eacute;fono de contacto:<strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"> {{ $total['phone'] }}</strong>
						<li>Ciudad de entrega:<strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"> {{ $total['shipping_city'] }}</strong>
						<li>Ciudad de Facturaci&oacute;n:<strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"> {{ $total['billing_city'] }}</strong>
						<li>Direcci&oacute;n IP de origen:<strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"> {{ $total['ip'] }}</strong>
						<li>M&eacute;todo de pago:<strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"> {{ $total['pay_method_name'] }}</strong>
				</ul>		 		
	  		 </div>
		   </div>
		   @else
		   <div class="row" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; margin-right: -15px; margin-left: -15px;">
				<div class="col-xs-12 text-justify" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; text-align: justify; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 100%;" align="justify"><h3 style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; orphans: 3; widows: 3; page-break-after: avoid; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; font-family: inherit; font-weight: 500; line-height: 1.1; margin-top: 20px; margin-bottom: 10px; font-size: 24px;"><pre style="overflow: auto; font-family: Menlo,Monaco,Consolas,'Courier New',monospace; font-size: 13px; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; page-break-inside: avoid; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; display: block; line-height: 1.42857143; word-break: break-all; word-wrap: break-word; border-radius: 4px; background-color: #f5f5f5; margin: 0 0 10px; padding: 9.5px; border: 1px solid #ccc;">
					@if ( $total['metpag']  == 1)
						Datos de pago - Contraentrega
					@else
						Datos de pago - Consignaci&oacute;n 
					@endif
					<ul type = square>
						<li>Direcci&oacute;n de entrega:<strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"> {{ $total['dirent'] }}</strong>
						<li>Tel&eacute;fono de contacto:<strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"> {{ $total['telent'] }}</strong>
						<li>Ciudad de entrega:<strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"> {{ $total['ciuent'] }}</strong>
						<li>Ciudad de Facturaci&oacute;n:<strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"> {{ $total['ciuent'] }}</strong>
						<li>Direcci&oacute;n IP de origen:<strong style="font-weight: 700; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;"> {{ $total['ip'] }}</strong>
				</ul>
			</div>
		   </div>		   
		   @endif
		   <br style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box;" />
		  <div class="row" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; margin-right: -15px; margin-left: -15px;">
				<div class="col-xs-12 text-center" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; text-align: center; position: relative; min-height: 1px; padding-right: 15px; padding-left: 15px; float: left; width: 100%;" align="center"><a href="localhost/ShoppingCart/public" class="btn btn-primary btn-lg" role="button" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; text-decoration: none; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; cursor: pointer; display: inline-block; margin-bottom: 0; font-size: 18px; font-weight: 400; line-height: 1.3333333; text-align: center; white-space: nowrap; vertical-align: middle; -ms-touch-action: manipulation; touch-action: manipulation; -webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; user-select: none; border-radius: 6px; background-image: none; background-color: #337ab7; padding: 10px 16px; border: 1px solid #2e6da4;">Te esperamos de nuevo!</a></div>
		   </div>
			<hr style="height: 0; -webkit-box-sizing: content-box; -moz-box-sizing: content-box; box-sizing: content-box; color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; margin-top: 20px; margin-bottom: 20px; border-top-color: #eee; border-top-style: solid; border-width: 1px 0 0;" />
			<a href="https://www.facebook.com/sharer/sharer.php?u=http://www.softecol.com/" target="_blank" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; text-decoration: none; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; background-color: transparent;"><img src="https://lh3.googleusercontent.com/-H8xMuAxM-bE/UefWwJr2vwI/AAAAAAAAEdY/N5I41q19KMk/s32-no/facebook.png" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; page-break-inside: avoid; max-width: 100% !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; vertical-align: middle; border: 0;" /></a>
			<a href="https://plus.google.com/share?url=http://www.softecol.com/" target="_blank" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; text-decoration: none; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; background-color: transparent;"><img src="https://lh5.googleusercontent.com/-5Q7Sj0SXhOA/UefWwcrnZ-I/AAAAAAAAEdg/auK3wqGCbZE/s32-no/googleplus.png" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; page-break-inside: avoid; max-width: 100% !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; vertical-align: middle; border: 0;" /></a>
			<a href="http://www.twitter.com/home?status=http://www.softecol.com/" target="_blank" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; text-decoration: none; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; background-color: transparent;"><img src="https://lh5.googleusercontent.com/-xZVxH6CsUaQ/UefWwgi8o3I/AAAAAAAAEdk/reo5XS6z8-8/s32-no/twitter.png" style="color: #000 !important; text-shadow: none !important; -webkit-box-shadow: none !important; box-shadow: none !important; page-break-inside: avoid; max-width: 100% !important; -webkit-box-sizing: border-box; -moz-box-sizing: border-box; box-sizing: border-box; vertical-align: middle; border: 0;" /></a>
		</div>
	</body>
</html>
